site_name: Birat Aryal Technical Docs
site_url: https://birataryal.github.io/
theme:
  name: material
  features: 
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.prune
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search

nav:
  - Home: index.md
  - Git: Git.md
  - About: about.md
